# Generated by Django 4.1.7 on 2023-03-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('ticket_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('image_url', models.TextField(null=True)),
                ('website_url', models.TextField(null=True)),
                ('social_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('website_url', models.TextField(null=True)),
                ('social_url', models.TextField(null=True)),
                ('event', models.ManyToManyField(related_name='performing_at', to='tickit.event')),
            ],
        ),
    ]
