# Generated by Django 4.1.7 on 2023-04-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0006_ticket_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ccv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
